apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc 
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  
