apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress-container
        image: wordpress:5.8.3-php7.4-apache
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
          - name: wordpress-data 
            mountPath: /var/www 
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql-service.default.svc.cluster.local
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: MYSQL_ROOT_PASSWORD
          - name: WORDPRESS_DB_USER
            value: root 
          - name: WORDPRESS_DB_NAME
            value: wordpress 
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: NodePort 
  selector:
    app: wordpress
  ports:
  - name: http 
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001

