---
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - 3000:80
    networks:
      - my_network
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=toor
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - my_network
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=root
      - MYSQL_PASSWORD=wordpress

networks:
  my_network:
